spring:
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: none
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driverClassName: ${DRIVER_CLASS}
  sql:
    init:
      platform: postgres
  flyway:
    enabled: true
    locations: classpath:db/migration
    validateOnMigrate: false
logging:
  level:
    org.hibernate.SQL: ERROR
    org.hibernate.type.descriptor.sql.BasicBinder: ERROR
    org.hibernate: ERROR
    org.flywaydb: INFO

server:
  port: ${SERVER_PORT}

scheduler:
  cron:
    daily:
      job: "0 0 0 * * ?"

jwt:
  token:
    validity: ${JWT_VALIDITY}
    prefix: ${JWT_PREFIX}
  signing:
    key: ${SIGNING_KEY}
  authorities:
    key: ${AUTHORITIES_KEY}

  header:
    string: ${HEADER_STRING}
  name:
    string: ${NAME_STRING}
