spring:
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: none
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driverClassName: ${DRIVER_CLASS}
  sql:
    init:
      platform: postgres
  flyway:
    enabled: true
    locations: classpath:db/migration
    validateOnMigrate: false
logging:
  level:
    org.hibernate.SQL: ERROR
    org.hibernate.type.descriptor.sql.BasicBinder: ERROR
    org.hibernate: ERROR
    org.flywaydb: INFO

server:
  port: ${SERVER_PORT}
  servlet:
    context-path: /api

scheduler:
  cron:
    daily:
      job: "0 0 0 * * ?"

jwt:
  token:
    validity: ${JWT_VALIDITY}
    prefix: ${JWT_PREFIX}
  signing:
    key: ${SIGNING_KEY}
  authorities:
    key: ${AUTHORITIES_KEY}

  header:
    string: ${HEADER_STRING}
  name:
    string: ${NAME_STRING}

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
    version: openapi_3_0
  swagger-ui:
    path: /api/swagger-ui/index.html
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
    filter: true
    urls:
      - url: /api/api-docs
        name: API Documentation
  show-actuator: false
  packages-to-scan: com.teapot.emarenda.rbac.controller,com.teapot.emarenda.controller
  paths-to-match: /**