spring:
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://localhost:15433/emarenda_db_local?currentSchema=dbo
    username: emarenda
    password: emarenda
    driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: postgres
  flyway:
    enabled: true
    locations: classpath:db/migration
    validateOnMigrate: false
logging:
  level:
    org.hibernate.SQL: ERROR
    org.hibernate.type.descriptor.sql.BasicBinder: ERROR
    org.hibernate: ERROR
    org.flywaydb: INFO

server:
  port: 8081

jwt:
  token:
    validity: 18000
    prefix: "Bearer"
  signing:
    key: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6InNvbWVBcHAiLCJpYXQiOjE1MTYyMzkwMjJ9.zJrqNzuqo4Z9WtPZQYTycE8Fw6fRJLJXv6MyKdJGOBE"
  authorities:
    key: "roles"

  header:
    string: "Authorization"
  name:
    string: "emarenda"
