spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://localhost:15433/demo_db_local
    username: demo
    password: demo
    driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: postgres
  flyway:
    enabled: true
    locations: classpath:db/migration
    validateOnMigrate: false
logging:
  level:
    org.flywaydb: INFO
    root: info
server:
  port: 8081

jwt:
  token:
    validity: 18000
    prefix: "Bearer"
  signing:
    key: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6InNvbWVBcHAiLCJpYXQiOjE1MTYyMzkwMjJ9.zJrqNzuqo4Z9WtPZQYTycE8Fw6fRJLJXv6MyKdJGOBE"
  authorities:
    key: "roles"
  permissions:
    key: "permissions"
  header:
    string: "Authorization"
